In [5]:
import pandas as pd

df = pd.read_csv('dados_filtrados.csv')
display(df)

,Series_Title,Released_Year,Certificate,Genre,IMDB_Rating,Overview,Meta_score,Director
0,The Shawshank Redemption,1994,A,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont
1,The Godfather,1972,A,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola
2,The Dark Knight,2008,UA,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan
3,The Godfather: Part II,1974,A,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola
4,12 Angry Men,1957,U,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet
...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,A,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards
996,Giant,1956,G,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens
997,From Here to Eternity,1953,Passed,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann
998,Lifeboat,1944,NaN,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock
999,The 39 Steps,1935,NaN,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock

In [6]:
df.fillna({'Certificate': 'Dado faltante'}, inplace=True)
display(df)

,Series_Title,Released_Year,Certificate,Genre,IMDB_Rating,Overview,Meta_score,Director
0,The Shawshank Redemption,1994,A,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont
1,The Godfather,1972,A,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola
2,The Dark Knight,2008,UA,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan
3,The Godfather: Part II,1974,A,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola
4,12 Angry Men,1957,U,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet
...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,A,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards
996,Giant,1956,G,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens
997,From Here to Eternity,1953,Passed,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann
998,Lifeboat,1944,Dado faltante,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock
999,The 39 Steps,1935,Dado faltante,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock

In [7]:
def fill_missing_meta_score(row):
    if pd.isnull(row['Meta_score']):
        return row['IMDB_Rating'] * 10  # Converter a escala do IMDB_Rating para a escala do Meta_score (que Ã© de 0 a 100)
    else:
        return row['Meta_score']

In [8]:
df['Meta_score'] = df.apply(fill_missing_meta_score, axis=1)

print(df.isnull().sum())

df.to_csv('dados_tratados.csv', index=False)

Series_Title     0
Released_Year    0
Certificate      0
Genre            0
IMDB_Rating      0
Overview         0
Meta_score       0
Director         0
dtype: int64